/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fastcourierservice.gui;

import command.interfaces.ICommand;
import command.interfaces.ICommandBehaviour;
import commandtracker.Command;
import datamodel.Address;
import datamodel.Customer;
import datamodel.CustomerList;
import datamodel.Delivery;
import fastcourierservice.commands.AddDeliveryCommand;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Brian
 */
public class AddNewDelivery extends javax.swing.JDialog {

    private CustomerList customers;
    private Customer customerToEdit;
    private FastCourierServiceGUI parent;
    private SpinnerModel packagesSpinModel;
    private SpinnerModel weightSpinModel;
    private SpinnerModel costSpinModel;

    /**
     * Creates new form AddNewDelivery
     */
    public AddNewDelivery(FastCourierServiceGUI parent, boolean modal) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.parent = parent;
        packagesSpinModel = new SpinnerNumberModel(1, 1, 10000, 1);
        weightSpinModel = new SpinnerNumberModel(0.1, 0.1, 1000, 0.1);
        costSpinModel = new SpinnerNumberModel(0.0, 0.0, 10000, 0.01);
        spnNoOfPackages.setModel(packagesSpinModel);
        spnWeight.setModel(weightSpinModel);
        spnCostPerKG.setModel(costSpinModel);
        spnCostPerKG.setEditor(new JSpinner.NumberEditor(spnCostPerKG, "0.00"));
        spnWeight.setEditor(new JSpinner.NumberEditor(spnWeight, "0.0"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainWindow = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        pblCollAddr = new javax.swing.JPanel();
        lblAddLine1Col = new javax.swing.JLabel();
        lblAddLine2Col = new javax.swing.JLabel();
        lblCityCol = new javax.swing.JLabel();
        lblPostcodeCol = new javax.swing.JLabel();
        txtColAddLine1 = new javax.swing.JTextField();
        txtColAddLine2 = new javax.swing.JTextField();
        txtColCity = new javax.swing.JTextField();
        txtColPostcode = new javax.swing.JTextField();
        lblDeliveryAddress = new javax.swing.JLabel();
        pnlDelAddr = new javax.swing.JPanel();
        lblAddLine1Del = new javax.swing.JLabel();
        lblAddLine2Del = new javax.swing.JLabel();
        lblCityDel = new javax.swing.JLabel();
        lblPostcodeDel = new javax.swing.JLabel();
        txtDelAddressLine1 = new javax.swing.JTextField();
        txtDelAddressLine2 = new javax.swing.JTextField();
        txtDelCity = new javax.swing.JTextField();
        txtDelPostcode = new javax.swing.JTextField();
        pnlCostPerKG = new javax.swing.JPanel();
        lblCostPerKG = new javax.swing.JLabel();
        spnCostPerKG = new javax.swing.JSpinner();
        lblCustomerNameDynamic = new javax.swing.JLabel();
        lblDeliveryDetails = new javax.swing.JLabel();
        pnlDeliveryDetails = new javax.swing.JPanel();
        lblNoOfPackages = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        spnNoOfPackages = new javax.swing.JSpinner();
        spnWeight = new javax.swing.JSpinner();
        lblHeading = new javax.swing.JLabel();
        txtConsNo = new javax.swing.JTextField();
        chkUseDefaultAdd = new javax.swing.JCheckBox();
        lblConsNo = new javax.swing.JLabel();
        lblCostPerKGPanel = new javax.swing.JLabel();
        lblCollectionAddress = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        chkUseCustomerCost = new javax.swing.JCheckBox();
        lblCustomerName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlMainWindow.setBackground(new java.awt.Color(199, 208, 213));

        btnSave.setBackground(new java.awt.Color(255, 113, 72));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        pblCollAddr.setBackground(new java.awt.Color(147, 177, 198));
        pblCollAddr.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAddLine1Col.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddLine1Col.setForeground(new java.awt.Color(255, 255, 255));
        lblAddLine1Col.setText("Address Line 1:");

        lblAddLine2Col.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddLine2Col.setForeground(new java.awt.Color(255, 255, 255));
        lblAddLine2Col.setText("Address Line 2:");

        lblCityCol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCityCol.setForeground(new java.awt.Color(255, 255, 255));
        lblCityCol.setText("City:");

        lblPostcodeCol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPostcodeCol.setForeground(new java.awt.Color(255, 255, 255));
        lblPostcodeCol.setText("Post Code:");

        txtColAddLine1.setBackground(new java.awt.Color(255, 242, 231));

        txtColAddLine2.setBackground(new java.awt.Color(255, 242, 231));

        txtColCity.setBackground(new java.awt.Color(255, 242, 231));

        txtColPostcode.setBackground(new java.awt.Color(255, 242, 231));

        javax.swing.GroupLayout pblCollAddrLayout = new javax.swing.GroupLayout(pblCollAddr);
        pblCollAddr.setLayout(pblCollAddrLayout);
        pblCollAddrLayout.setHorizontalGroup(
            pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblCollAddrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblCollAddrLayout.createSequentialGroup()
                        .addComponent(lblAddLine1Col)
                        .addGap(18, 18, 18)
                        .addComponent(txtColAddLine1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addGroup(pblCollAddrLayout.createSequentialGroup()
                        .addGroup(pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddLine2Col)
                            .addComponent(lblCityCol)
                            .addComponent(lblPostcodeCol))
                        .addGap(18, 18, 18)
                        .addGroup(pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtColAddLine2)
                            .addComponent(txtColPostcode)
                            .addComponent(txtColCity))))
                .addContainerGap())
        );
        pblCollAddrLayout.setVerticalGroup(
            pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblCollAddrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLine1Col)
                    .addComponent(txtColAddLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLine2Col)
                    .addComponent(txtColAddLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityCol)
                    .addComponent(txtColCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pblCollAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostcodeCol)
                    .addComponent(txtColPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblDeliveryAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDeliveryAddress.setForeground(new java.awt.Color(236, 88, 58));
        lblDeliveryAddress.setText("Delivery Address:");

        pnlDelAddr.setBackground(new java.awt.Color(147, 177, 198));
        pnlDelAddr.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAddLine1Del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddLine1Del.setForeground(new java.awt.Color(255, 255, 255));
        lblAddLine1Del.setText("Address Line 1:");

        lblAddLine2Del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddLine2Del.setForeground(new java.awt.Color(255, 255, 255));
        lblAddLine2Del.setText("Address Line 2:");

        lblCityDel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCityDel.setForeground(new java.awt.Color(255, 255, 255));
        lblCityDel.setText("City:");

        lblPostcodeDel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPostcodeDel.setForeground(new java.awt.Color(255, 255, 255));
        lblPostcodeDel.setText("Post Code:");

        txtDelAddressLine1.setBackground(new java.awt.Color(255, 242, 231));

        txtDelAddressLine2.setBackground(new java.awt.Color(255, 242, 231));

        txtDelCity.setBackground(new java.awt.Color(255, 242, 231));

        txtDelPostcode.setBackground(new java.awt.Color(255, 242, 231));

        javax.swing.GroupLayout pnlDelAddrLayout = new javax.swing.GroupLayout(pnlDelAddr);
        pnlDelAddr.setLayout(pnlDelAddrLayout);
        pnlDelAddrLayout.setHorizontalGroup(
            pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDelAddrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDelAddrLayout.createSequentialGroup()
                        .addComponent(lblAddLine1Del)
                        .addGap(18, 18, 18)
                        .addComponent(txtDelAddressLine1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                    .addGroup(pnlDelAddrLayout.createSequentialGroup()
                        .addGroup(pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddLine2Del)
                            .addComponent(lblCityDel)
                            .addComponent(lblPostcodeDel))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDelAddressLine2)
                            .addComponent(txtDelCity)
                            .addComponent(txtDelPostcode))))
                .addContainerGap())
        );
        pnlDelAddrLayout.setVerticalGroup(
            pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDelAddrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLine1Del)
                    .addComponent(txtDelAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLine2Del)
                    .addComponent(txtDelAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityDel)
                    .addComponent(txtDelCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDelAddrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostcodeDel)
                    .addComponent(txtDelPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCostPerKG.setBackground(new java.awt.Color(147, 177, 198));
        pnlCostPerKG.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCostPerKG.setPreferredSize(new java.awt.Dimension(300, 77));

        lblCostPerKG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCostPerKG.setForeground(new java.awt.Color(255, 255, 255));
        lblCostPerKG.setText("Cost per KG:");

        javax.swing.GroupLayout pnlCostPerKGLayout = new javax.swing.GroupLayout(pnlCostPerKG);
        pnlCostPerKG.setLayout(pnlCostPerKGLayout);
        pnlCostPerKGLayout.setHorizontalGroup(
            pnlCostPerKGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCostPerKGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCostPerKG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(spnCostPerKG, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        pnlCostPerKGLayout.setVerticalGroup(
            pnlCostPerKGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCostPerKGLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlCostPerKGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostPerKG)
                    .addComponent(spnCostPerKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCustomerNameDynamic.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblCustomerNameDynamic.setForeground(new java.awt.Color(236, 88, 58));
        lblCustomerNameDynamic.setText("Name Here");

        lblDeliveryDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDeliveryDetails.setForeground(new java.awt.Color(236, 88, 58));
        lblDeliveryDetails.setText("Delivery Details:");

        pnlDeliveryDetails.setBackground(new java.awt.Color(147, 177, 198));
        pnlDeliveryDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNoOfPackages.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNoOfPackages.setForeground(new java.awt.Color(255, 255, 255));
        lblNoOfPackages.setText("No. of Packages:");

        lblWeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(255, 255, 255));
        lblWeight.setText("Weight (KG):");

        javax.swing.GroupLayout pnlDeliveryDetailsLayout = new javax.swing.GroupLayout(pnlDeliveryDetails);
        pnlDeliveryDetails.setLayout(pnlDeliveryDetailsLayout);
        pnlDeliveryDetailsLayout.setHorizontalGroup(
            pnlDeliveryDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeliveryDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDeliveryDetailsLayout.createSequentialGroup()
                        .addComponent(lblWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDeliveryDetailsLayout.createSequentialGroup()
                        .addComponent(lblNoOfPackages)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnNoOfPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDeliveryDetailsLayout.setVerticalGroup(
            pnlDeliveryDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeliveryDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeliveryDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoOfPackages)
                    .addComponent(spnNoOfPackages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDeliveryDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(spnWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblHeading.setFont(new java.awt.Font("Garamond", 1, 40)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 90, 9));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Add a New Delivery");

        txtConsNo.setEditable(false);
        txtConsNo.setBackground(new java.awt.Color(199, 208, 213));
        txtConsNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtConsNo.setForeground(new java.awt.Color(236, 88, 58));
        txtConsNo.setText("Cons No Here");
        txtConsNo.setBorder(null);

        chkUseDefaultAdd.setBackground(new java.awt.Color(199, 208, 213));
        chkUseDefaultAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkUseDefaultAdd.setForeground(new java.awt.Color(236, 88, 58));
        chkUseDefaultAdd.setText("Use Default Address");
        chkUseDefaultAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUseDefaultAddActionPerformed(evt);
            }
        });

        lblConsNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConsNo.setForeground(new java.awt.Color(236, 88, 58));
        lblConsNo.setText("Consignment No:");

        lblCostPerKGPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCostPerKGPanel.setForeground(new java.awt.Color(236, 88, 58));
        lblCostPerKGPanel.setText("Cost per KG:");

        lblCollectionAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCollectionAddress.setForeground(new java.awt.Color(236, 88, 58));
        lblCollectionAddress.setText("Collection Address:");

        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));

        btnCancel.setBackground(new java.awt.Color(255, 113, 72));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        chkUseCustomerCost.setBackground(new java.awt.Color(199, 208, 213));
        chkUseCustomerCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkUseCustomerCost.setForeground(new java.awt.Color(236, 88, 58));
        chkUseCustomerCost.setSelected(true);
        chkUseCustomerCost.setText("Use Customer Default");
        chkUseCustomerCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUseCustomerCostActionPerformed(evt);
            }
        });

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(236, 88, 58));
        lblCustomerName.setText("Customer Name:");

        javax.swing.GroupLayout pnlMainWindowLayout = new javax.swing.GroupLayout(pnlMainWindow);
        pnlMainWindow.setLayout(pnlMainWindowLayout);
        pnlMainWindowLayout.setHorizontalGroup(
            pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(lblHeading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainWindowLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainWindowLayout.createSequentialGroup()
                        .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pblCollAddr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDeliveryDetails)
                            .addGroup(pnlMainWindowLayout.createSequentialGroup()
                                .addComponent(lblCollectionAddress)
                                .addGap(18, 18, 18)
                                .addComponent(chkUseDefaultAdd))
                            .addComponent(pnlDeliveryDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnlDelAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDeliveryAddress)
                                .addGroup(pnlMainWindowLayout.createSequentialGroup()
                                    .addComponent(lblCostPerKGPanel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkUseCustomerCost)
                                    .addGap(29, 29, 29)))
                            .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlMainWindowLayout.createSequentialGroup()
                                    .addComponent(btnCancel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSave))
                                .addComponent(pnlCostPerKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(pnlMainWindowLayout.createSequentialGroup()
                        .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsNo)
                            .addComponent(lblCustomerName))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainWindowLayout.createSequentialGroup()
                                .addComponent(txtConsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlMainWindowLayout.createSequentialGroup()
                                .addComponent(lblCustomerNameDynamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        pnlMainWindowLayout.setVerticalGroup(
            pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerNameDynamic, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerName))
                .addGap(23, 23, 23)
                .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMainWindowLayout.createSequentialGroup()
                        .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConsNo)
                            .addComponent(txtConsNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCollectionAddress)
                            .addComponent(chkUseDefaultAdd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pblCollAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainWindowLayout.createSequentialGroup()
                        .addComponent(lblDeliveryAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlDelAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryDetails)
                    .addComponent(lblCostPerKGPanel)
                    .addComponent(chkUseCustomerCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCostPerKG, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(pnlDeliveryDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveDelivery();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chkUseDefaultAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUseDefaultAddActionPerformed
        if (chkUseDefaultAdd.isSelected()) {
            txtColAddLine1.setText(customerToEdit.getColAddress().getAddressLine1());
            txtColAddLine2.setText(customerToEdit.getColAddress().getAddressLine2());
            txtColCity.setText(customerToEdit.getColAddress().getCity());
            txtColPostcode.setText(customerToEdit.getColAddress().getPostcode());
            txtColAddLine1.setEnabled(false);
            txtColAddLine2.setEnabled(false);
            txtColCity.setEnabled(false);
            txtColPostcode.setEnabled(false);
        } else {
            txtColAddLine1.setText("");
            txtColAddLine2.setText("");
            txtColCity.setText("");
            txtColPostcode.setText("");
            txtColAddLine1.setEnabled(true);
            txtColAddLine2.setEnabled(true);
            txtColCity.setEnabled(true);
            txtColPostcode.setEnabled(true);
        }
    }//GEN-LAST:event_chkUseDefaultAddActionPerformed

    private void chkUseCustomerCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUseCustomerCostActionPerformed
        setCustomerDeliveryCost();
    }//GEN-LAST:event_chkUseCustomerCostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewDelivery dialog = new AddNewDelivery(new FastCourierServiceGUI(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkUseCustomerCost;
    private javax.swing.JCheckBox chkUseDefaultAdd;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddLine1Col;
    private javax.swing.JLabel lblAddLine1Del;
    private javax.swing.JLabel lblAddLine2Col;
    private javax.swing.JLabel lblAddLine2Del;
    private javax.swing.JLabel lblCityCol;
    private javax.swing.JLabel lblCityDel;
    private javax.swing.JLabel lblCollectionAddress;
    private javax.swing.JLabel lblConsNo;
    private javax.swing.JLabel lblCostPerKG;
    private javax.swing.JLabel lblCostPerKGPanel;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerNameDynamic;
    private javax.swing.JLabel lblDeliveryAddress;
    private javax.swing.JLabel lblDeliveryDetails;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblNoOfPackages;
    private javax.swing.JLabel lblPostcodeCol;
    private javax.swing.JLabel lblPostcodeDel;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JPanel pblCollAddr;
    private javax.swing.JPanel pnlCostPerKG;
    private javax.swing.JPanel pnlDelAddr;
    private javax.swing.JPanel pnlDeliveryDetails;
    private javax.swing.JPanel pnlMainWindow;
    private javax.swing.JSpinner spnCostPerKG;
    private javax.swing.JSpinner spnNoOfPackages;
    private javax.swing.JSpinner spnWeight;
    private javax.swing.JTextField txtColAddLine1;
    private javax.swing.JTextField txtColAddLine2;
    private javax.swing.JTextField txtColCity;
    private javax.swing.JTextField txtColPostcode;
    private javax.swing.JTextField txtConsNo;
    private javax.swing.JTextField txtDelAddressLine1;
    private javax.swing.JTextField txtDelAddressLine2;
    private javax.swing.JTextField txtDelCity;
    private javax.swing.JTextField txtDelPostcode;
    // End of variables declaration//GEN-END:variables

    private void setCustomerDeliveryCost() {
        if (this.chkUseCustomerCost.isSelected()) {
            spnCostPerKG.setValue(customerToEdit.getDeliveryCost());
            spnCostPerKG.setEnabled(false);
        } else {
            spnCostPerKG.setEnabled(true);
        }
    }

    public void setCustomerList(CustomerList objCustomers) {
        customers = objCustomers;
    }

    public void setEditableCustomer(int customerIndex) {
        customerToEdit = customers.getCustomerAt(customerIndex);
        lblCustomerNameDynamic.setText(customerToEdit.getFullName());
        txtConsNo.setText(customers.getNewConsNo());
        setCustomerDeliveryCost();
    }

    private void saveDelivery() {
        if (isSaveable()) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Are you sure you want to save this Delivery?",
                    "Warning", dialogButton);

            if (dialogResult == JOptionPane.YES_OPTION) {
                Address colAddress = new Address(txtColAddLine1.getText(),
                        txtColAddLine2.getText(),
                        txtColCity.getText(),
                        txtColPostcode.getText());

                Address delAddress = new Address(txtDelAddressLine1.getText(),
                        txtDelAddressLine2.getText(),
                        txtDelCity.getText(),
                        txtDelPostcode.getText());

                double weight = (double) spnWeight.getValue();
                int noOfPackages = (int) spnNoOfPackages.getValue();
                double costPerKg = (double) spnCostPerKG.getValue();

                Delivery newDelivery = new Delivery(txtConsNo.getText(),
                        noOfPackages,
                        weight,
                        colAddress,
                        delAddress);

                if (costPerKg != Delivery.DEFAULTCOST) {
                    ICommandBehaviour objAdd = new AddDeliveryCommand(newDelivery,
                            costPerKg, customerToEdit);
                    ICommand objCommand = new Command(objAdd);
                    parent.executeCommand(objCommand);
                    this.parent.checkUndoRedo();
                } else {
                    ICommandBehaviour objAdd = new AddDeliveryCommand(newDelivery,
                            customerToEdit);
                    ICommand objCommand = new Command(objAdd);
                    parent.executeCommand(objCommand);
                    this.parent.checkUndoRedo();
                }
                this.dispose();
            }
        }
    }

    private Boolean isSaveable() {
        Boolean blnValid = false;
        try {
            if (txtColAddLine1.getText().length() == 0) {
                throw new IllegalArgumentException("Collection Address Line 1 is invalid!");
            }
            if (txtColCity.getText().length() == 0) {
                throw new IllegalArgumentException("Collection City is invalid!");
            }
            if (!txtColPostcode.getText().matches(
                    "^([A-PR-UWYZ0-9][A-HK-Y0-9][AEHMNPRTVXY0-9]?[ABEHMNPRVWXY0-9]"
                    + "? {1,2}[0-9][ABD-HJLN-UW-Z]{2}|GIR 0AA)$")) {
                throw new IllegalArgumentException("Post Code is invalid!\nPlease "
                        + "use a space between the first and second part e.g. PL1 2PD");
            }
            if (txtDelAddressLine1.getText().length() == 0) {
                throw new IllegalArgumentException("Delivery Address Line 1 is invalid!");
            }
            if (txtDelCity.getText().length() == 0) {
                throw new IllegalArgumentException("Delivery City is invalid!");
            }
            if (!txtDelPostcode.getText().matches(
                    "^([A-PR-UWYZ](([0-9](([0-9]|[A-HJKSTUW])?)?)|([A-HK-Y][0-9]"
                    + "([0-9]|[ABEHMNPRVWXY])?)) [0-9][ABD-HJLNP-UW-Z]{2})")) {
                
                throw new IllegalArgumentException("Post Code is case sensitive."
                        + "\nPlease also use a space between the first and second "
                        + "part e.g. PL1 2PD");
            }
            blnValid = true;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "The provided data is invalid",
                    "Error reading data", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Invalid Data!", JOptionPane.ERROR_MESSAGE);
        }
        return blnValid;
    }
}
