/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fastcourierservice.gui;

import datamodel.Customer;
import datamodel.CustomerList;
import datamodel.Delivery;
import datamodel.DeliveryStatus;
import java.awt.Dialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import observerpattern.IObserver;

/**
 *
 * @author Brian
 */
public class CustomerDeliveries extends javax.swing.JDialog implements IObserver {

    private CustomerList customers;
    private Customer customerToEdit;
    private CustomerDeliveriesType windowType;
    private DefaultComboBoxModel<Delivery> model;
    private FastCourierServiceGUI parent;

    /**
     * Creates new form CustomerDeliveries
     */
    public CustomerDeliveries(FastCourierServiceGUI parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public CustomerDeliveries(FastCourierServiceGUI parent, boolean modal,
            CustomerDeliveriesType function) {
        this(parent, modal);
        windowType = function;
        this.parent = parent;
        switch (this.windowType) {
            case COMPLETED:
                lblHeading.setText("Completed Customer Deliveries");
                this.btnSetDelivered.setVisible(false);
                this.btnUpdateStatus.setVisible(false);
                break;
            case INCOMPLETE:
                lblHeading.setText("Incomplete Customer Deliveries");
                break;
        }

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent ev) {
                onClose();
            }
        });
    }

    private void onClose() {
        this.customers.removeObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCustomerName = new javax.swing.JLabel();
        lblStatusDisplayed = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHeading = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        notesDisplay = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveryAddressDisplay = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        collectionAddressDisplay = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cbxDeliveries = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTotalCost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCostPerKg = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtNoOfPackages = new javax.swing.JTextField();
        txtDeliveredDate = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSetDelivered = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();
        lblCustomerName1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(199, 208, 213));

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(236, 88, 58));
        lblCustomerName.setText("Name Here");

        lblStatusDisplayed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStatusDisplayed.setForeground(new java.awt.Color(236, 88, 58));
        lblStatusDisplayed.setText("Status Here");

        jSeparator1.setForeground(new java.awt.Color(255, 153, 0));

        lblHeading.setFont(new java.awt.Font("Garamond", 1, 40)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 90, 9));
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Customer Deliveries");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 88, 58));
        jLabel8.setText("Status:");

        jPanel2.setBackground(new java.awt.Color(147, 177, 198));

        notesDisplay.setEditable(false);
        notesDisplay.setBackground(new java.awt.Color(240, 240, 240));
        notesDisplay.setColumns(20);
        notesDisplay.setRows(5);
        jScrollPane4.setViewportView(notesDisplay);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Notes:");

        deliveryAddressDisplay.setEditable(false);
        deliveryAddressDisplay.setBackground(new java.awt.Color(240, 240, 240));
        deliveryAddressDisplay.setColumns(20);
        deliveryAddressDisplay.setRows(5);
        jScrollPane2.setViewportView(deliveryAddressDisplay);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Delivery Address:");

        collectionAddressDisplay.setEditable(false);
        collectionAddressDisplay.setBackground(new java.awt.Color(240, 240, 240));
        collectionAddressDisplay.setColumns(20);
        collectionAddressDisplay.setRows(5);
        jScrollPane1.setViewportView(collectionAddressDisplay);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Collection Address:");

        cbxDeliveries.setBackground(new java.awt.Color(255, 90, 9));
        cbxDeliveries.setForeground(new java.awt.Color(255, 255, 255));
        cbxDeliveries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxDeliveries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDeliveriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbxDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxDeliveries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 88, 58));
        jLabel1.setText("Select a Delivery:");

        jPanel3.setBackground(new java.awt.Color(147, 177, 198));

        txtTotalCost.setEditable(false);
        txtTotalCost.setBackground(new java.awt.Color(255, 242, 231));
        txtTotalCost.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Cost:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cost per KG:");

        txtCostPerKg.setEditable(false);
        txtCostPerKg.setBackground(new java.awt.Color(255, 242, 231));

        txtWeight.setEditable(false);
        txtWeight.setBackground(new java.awt.Color(255, 242, 231));

        txtNoOfPackages.setEditable(false);
        txtNoOfPackages.setBackground(new java.awt.Color(255, 242, 231));

        txtDeliveredDate.setEditable(false);
        txtDeliveredDate.setBackground(new java.awt.Color(255, 242, 231));

        txtStartDate.setEditable(false);
        txtStartDate.setBackground(new java.awt.Color(255, 242, 231));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Start Date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Delivered Date:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number of Packages:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Weight:");

        btnSetDelivered.setBackground(new java.awt.Color(255, 113, 72));
        btnSetDelivered.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSetDelivered.setForeground(new java.awt.Color(255, 255, 255));
        btnSetDelivered.setText("Set as Delivered");
        btnSetDelivered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetDeliveredActionPerformed(evt);
            }
        });

        btnUpdateStatus.setBackground(new java.awt.Color(255, 113, 72));
        btnUpdateStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUpdateStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoOfPackages)
                            .addComponent(txtDeliveredDate)
                            .addComponent(txtCostPerKg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSetDelivered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtWeight)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateStatus)
                    .addComponent(btnSetDelivered))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDeliveredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoOfPackages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCostPerKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCustomerName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCustomerName1.setForeground(new java.awt.Color(236, 88, 58));
        lblCustomerName1.setText("Customer Name:");

        btnClose.setBackground(new java.awt.Color(255, 113, 72));
        btnClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCustomerName1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatusDisplayed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(btnClose))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerName1))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatusDisplayed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cbxDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDeliveriesActionPerformed
        showDeliveryDetails();
    }//GEN-LAST:event_cbxDeliveriesActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        UpdateStatus objWindow = new UpdateStatus(this, parent,
            "", Dialog.ModalityType.APPLICATION_MODAL);
        objWindow.setDelivery(model.getElementAt(cbxDeliveries.getSelectedIndex()));
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnSetDeliveredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetDeliveredActionPerformed
        UpdateStatus objWindow = new UpdateStatus(this, parent,
            "", Dialog.ModalityType.APPLICATION_MODAL);
        objWindow.setDelivery(model.getElementAt(cbxDeliveries.getSelectedIndex()));
        objWindow.setDelivered(true);
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnSetDeliveredActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDeliveries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDeliveries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDeliveries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDeliveries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerDeliveries dialog = new CustomerDeliveries(new FastCourierServiceGUI(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSetDelivered;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JComboBox cbxDeliveries;
    private javax.swing.JTextArea collectionAddressDisplay;
    private javax.swing.JTextArea deliveryAddressDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerName1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblStatusDisplayed;
    private javax.swing.JTextArea notesDisplay;
    private javax.swing.JTextField txtCostPerKg;
    private javax.swing.JTextField txtDeliveredDate;
    private javax.swing.JTextField txtNoOfPackages;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    public void setEditableCustomer(int customerIndex) {
        this.customerToEdit = this.customers.getCustomerAt(customerIndex);
        this.lblCustomerName.setText(this.customerToEdit.getFullName());
        rebuildComboBox();
        this.update();
    }

    @Override
    public void update() {
        if (null != this.customers) {
            rebuildComboBox();
            showDeliveryDetails();
        }
    }

    public void setCustomers(CustomerList customers) {
        if (null != this.customers) {
            this.customers.removeObserver(this);
            this.customers = null;
        }
        this.customers = customers;
        if (null != this.customers) {
            this.customers.registerObserver(this);
        }
    }

    private void rebuildComboBox() {
        model = new DefaultComboBoxModel<>();
        Object selectedItemInOldBox = cbxDeliveries.getSelectedItem();
        if (null != customerToEdit) {
            switch (windowType) {
                case INCOMPLETE:
                    for (int i = 0; i < customerToEdit.getNoOfDeliveries(); i++) {
                        Delivery tempDelivery = customerToEdit.getDeliveryAt(i);
                        if (customerToEdit.getDeliveryAt(i) != null) {
                            if (tempDelivery.getStatus().equals(DeliveryStatus.PENDINGCOLLECTION)
                                    || tempDelivery.getStatus().equals(DeliveryStatus.INTRANSIT)
                                    || tempDelivery.getStatus().equals(DeliveryStatus.DELIVERYREFUSED)) {

                                model.addElement(tempDelivery);
                            }
                        }
                    }
                    break;
                case COMPLETED:
                    for (int i = 0; i < customerToEdit.getNoOfDeliveries(); i++) {
                        Delivery tempDelivery = customerToEdit.getDeliveryAt(i);
                        if (customerToEdit.getDeliveryAt(i) != null) {
                            if (tempDelivery.getStatus().equals(DeliveryStatus.UNDELIVERABLE)
                                    || tempDelivery.getStatus().equals(DeliveryStatus.DELIVERED)) {

                                model.addElement(tempDelivery);
                            }
                        }
                    }
                    break;
            }
        }
        cbxDeliveries.setModel(model);
        if (model.getSize()
                > 0) {
            if (null != selectedItemInOldBox) {
                cbxDeliveries.setSelectedItem(selectedItemInOldBox);
            } else {
                cbxDeliveries.setSelectedIndex(0);
            }
            showDeliveryDetails();
        } else {
            this.dispose();
        }
    }

    private void showDeliveryDetails() {
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        DecimalFormat decF = new DecimalFormat("0.00");
        if (null != customerToEdit) {
            Delivery selectedDelivery = model.getElementAt(cbxDeliveries.getSelectedIndex());
            if (null != selectedDelivery) {
                StringBuilder resultBuilder = new StringBuilder();
                resultBuilder.append(selectedDelivery.getColAddress().getAddressLine1());
                resultBuilder.append("\n");
                resultBuilder.append(selectedDelivery.getColAddress().getAddressLine2());
                resultBuilder.append("\n");
                resultBuilder.append(selectedDelivery.getColAddress().getCity());
                resultBuilder.append("\n");
                resultBuilder.append(selectedDelivery.getColAddress().getPostcode());
                collectionAddressDisplay.setText(resultBuilder.toString());

                resultBuilder = new StringBuilder();
                resultBuilder.append(selectedDelivery.getDelAddress().getAddressLine1());
                resultBuilder.append("\n");
                resultBuilder.append(selectedDelivery.getDelAddress().getAddressLine2());
                resultBuilder.append("\n");
                resultBuilder.append(selectedDelivery.getDelAddress().getCity());
                resultBuilder.append("\n");
                resultBuilder.append(selectedDelivery.getDelAddress().getPostcode());
                deliveryAddressDisplay.setText(resultBuilder.toString());

                txtCostPerKg.setText("£" + decF.format(
                        selectedDelivery.getCostPerKg()));
                txtTotalCost.setText("£" + decF.format(
                        selectedDelivery.getTotalCost()));
                txtWeight.setText(Double.toString(
                        selectedDelivery.getWeight()));
                txtNoOfPackages.setText(
                        Integer.toString(selectedDelivery.getNoOfPackages()));
                txtStartDate.setText(df.format(
                        selectedDelivery.getStartDate()));
                Date deliveredDate = selectedDelivery.getDeliveredDate();
                if (null != deliveredDate) {
                    txtDeliveredDate.setText(df.format(deliveredDate));
                } else {
                    txtDeliveredDate.setText("");
                }
                
                lblStatusDisplayed.setText(selectedDelivery.getStatus().toString());
                notesDisplay.setText(selectedDelivery.getNotes());
            }
        }
    }
}
